// <auto-generated />
namespace WebPresent.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class givennamesurnamestartdateactive : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(givennamesurnamestartdateactive));
        
        string IMigrationMetadata.Id
        {
            get { return "202104121805316_givenname, surname, startdate, active"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
